spring.application.name=backend21

spring.datasource.url=jdbc:sqlserver://sql-server-master.database.windows.net:1433;database=blockchain-project;user=master-sql-server@sql-server-master;password=uu9fnezpgtMas;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=master-sql-server
spring.datasource.password=uu9fnezpgtMas


spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

